language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "hhvm"

install:
  - composer install --dev
  - composer show -i
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:

script:
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr1,psr2 src;
  - ./vendor/bin/php-cs-fixer fix -v --dry-run --fixers=-psr0,psr1,psr2 tests;
  - ./vendor/bin/phpunit -c $TRAVIS_BUILD_DIR/tests/phpunit.xml
  - ./vendor/bin/phpcs -n --standard=PSR2 ./src/ ./tests/


after_script:
  - php ocular.phar code-coverage:upload --format=php-clover tests/log/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.6
    - php: hhvm
